services:
  minio:
    restart: always
    image: minio/minio
    container_name: mlflow_s3
    platform: linux/arm64
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data/minio:/data
    networks:
      - recsys

  mlflow_mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: mlflow_mc
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /tmp/wait-for-it.sh minio:9000 &&
      /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
      /usr/bin/mc mb minio/mlflow &&
      /usr/bin/mc mb minio/data &&
      /usr/bin/mc mb minio/runs;
      exit 0;
      "
    volumes:
      - ./mlflow/wait-for-it.sh:/tmp/wait-for-it.sh
    networks:
      - recsys

  mlflow_db:
    restart: always
    image: mysql/mysql-server:8.0.23
    container_name: mlflow_db
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mlflow/dbdata:/var/lib/mysql
    networks:
      - recsys

  mlflow_server:
    restart: always
    # Need to build MLflow because the official Docker image does not come with pymysql installed
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - mlflow_mc
      - mlflow_db
    ports:
      - "5002:5000"
    environment:
      # Somehow the MLFLOW_S3_ENDPOINT_URL must be minio instead of a custom name like mlflow_s3 for the service because if the endpoint is not `minio` then boto3 would raise error
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: >
      mlflow server
        --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow_db:3306/${MYSQL_DATABASE}
        --artifacts-destination s3://mlflow
        --serve-artifacts
        --host 0.0.0.0
        --port 5000
    networks:
      - recsys

  kv_store:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: kv_store
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    networks:
      - recsys

  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage:z
    restart: always
    networks:
      - recsys

  dwh:
    container_name: dwh
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
       # Run scripts to create schemas upon startup
       - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - recsys

  # feature_online_server:
  #   container_name: feature_online_server
  #   build:
  #     context: .
  #     dockerfile: feature_pipeline.Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=138.2.61.6
  #   ports:
  #     - "${FEAST_ONLINE_SERVER_PORT:-6566}:${FEAST_ONLINE_SERVER_PORT:-6566}"
  #   working_dir: /app/feature_pipeline/feature_store/feature_repo
  #   entrypoint: ["feast", "serve", "--port", "${FEAST_ONLINE_SERVER_PORT:-6566}", "--host", "0.0.0.0"]
  #   restart: always

  # feature_offline_server:
  #   container_name: feature_offline_server
  #   build:
  #     context: .
  #     dockerfile: feature_pipeline.Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=138.2.61.6
  #   ports:
  #     - "${FEAST_OFFLINE_SERVER_PORT:-8815}:${FEAST_OFFLINE_SERVER_PORT:-8815}"
  #   working_dir: /app/feature_pipeline/feature_store/feature_repo
  #   entrypoint: ["feast", "serve_offline", "--port", "${FEAST_OFFLINE_SERVER_PORT:-8815}", "--host", "0.0.0.0"]
  #   restart: always

  # feature_store_ui:
  #   container_name: feature_store_ui
  #   build:
  #     context: .
  #     dockerfile: feature_pipeline.Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=138.2.61.6
  #   ports:
  #     - "${FEAST_UI_PORT:-8887}:${FEAST_UI_PORT:-8887}"
  #   working_dir: /app/feature_pipeline/feature_store/feature_repo
  #   entrypoint: ["feast", "ui", "--port", "${FEAST_UI_PORT:-8887}", "--host", "0.0.0.0"]
  #   restart: always


networks:
  recsys:
    driver: bridge
