services:
  api:
    container_name: api
    build:
      context: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=kv_store
      # - SEQRP_MODEL_SERVER_URL=http://seqrp_model_server:3000
      # - FEAST_ONLINE_SERVER_HOST=feature_online_server
    # volumes:
    #   - ./api:/app/api
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - recsys
    restart: always

  seq_retriever_model_server:
    container_name: seq_retriever_model_server
    build:
      context: .
      dockerfile: model_server/Dockerfile
    ports:
      - "30000:3000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://138.2.61.6:5002
    entrypoint: ["bentoml", "serve", "sequence_service:TwoTowerService"]
    # command: ["ls"]

networks:
  recsys:
    external: true
    name: real_time_recsys_recsys
    
